version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - printenv
      - echo "@webonyx:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      - echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ~/.npmrc
      - cat ~/.npmrc
      - yarn add @webonyx/react-atlas@^2.1.21,
      - yarn install
