name: Changelog

on:
  pull_request:
    types: [ opened ]
    branches: [ master ]

jobs:
  auto:
    name: Changelog
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'develop' || startsWith(github.head_ref, 'release') }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VIET_PAT_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 10
        ref: ${{ github.head_ref }}
        token: ${{ secrets.MY_GITHUB_PAT }}

    - name: Prepare repository
      run: git fetch --depth 100 --tags

    - name: Prepare auto
      run: |
        npm install --global --no-fund --no-audit auto@10.37.6

    - name: "Make changelog"
      run: |
        which auto
        export PATH="$(npm bin -g):$PATH"
        set -xe
        if auto label --pr ${{github.event.number}} --exists release; then
          auto changelog
          git push
          sleep 3
          GH_TOKEN=$VIET_PAT_TOKEN gh pr merge ${{github.event.number}} --auto --merge
          echo The PR should be merged
        else
          echo [Skipped] No "release" label found
          exit 0
        fi
        
