name: Changelog

on:
  pull_request:
    types: [ opened ]
    branches: [ master ]

jobs:
  auto:
    name: Changelog
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'develop' || startsWith(github.head_ref, 'release') }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VIET_PAT_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 10
        ref: ${{ github.head_ref }}
        token: ${{ secrets.MY_GITHUB_PAT }}

    - name: Prepare repository
      run: git fetch --depth 100 --tags

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Prepare auto
      run: |
        yarn global add auto@10.37.6 auto-plugin-package-json

    - name: "Make changelog"
      run: |
        set -xe
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        if yarn auto label --pr $PR_NUMBER --exists release; then
          yarn auto changelog
          git push
          sleep 5
          GH_TOKEN=$VIET_PAT_TOKEN gh pr merge $PR_NUMBER --auto --delete-branch
          echo The PR should be merged
        else
          echo [Skipped] No "release" label found
          exit 0
        fi
        
