name: Changelog

on:
  pull_request:
    types: [ opened, labeled ]
    branches: [ master ]

jobs:
  auto:
    name: Auto
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'develop' && !contains(github.event.head_commit.message, 'skip ci') }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VIET_PAT_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 10
        ref: ${{ github.head_ref }}
        token: ${{ secrets.MY_GITHUB_PAT }}

    - name: Prepare repository
      run: git fetch --depth 100 --tags

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Prepare auto
      run: |
        yarn global add auto@10.37.6 auto-plugin-package-json

    - name: "Make changelog"
      run: |
        set -xe
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        if yarn auto label --pr $PR_NUMBER --exists release; then
          yarn auto changelog --verbose
          git pull --rebase origin $GITHUB_HEAD_REF
          git push -u origin $GITHUB_HEAD_REF
          sleep 5
          GH_TOKEN=$VIET_PAT_TOKEN gh pr merge $PR_NUMBER --auto --merge
          echo The PR should be merged
        fi
        
